apiVersion: v1
kind: Secret
metadata:
  namespace: dev-k8s
  name: db-credentials
type: Opaque
data:
  # secretos codificados en base64
  mariadb-root-password: bWljaWxhdmU=    # "miclave"
  mariadb-user-password: d3BwYXNz         # "wppass"
  mariadb-user: d3B1c2Vy                  # "wpuser"