apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: dev-k8s
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080