apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: dev-k8s
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30088