apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: dev-k8s
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PMA_HOST
              value: mariadb.dev-k8s.svc.cluster.local
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80